name: Quality check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  driver-quality:
    uses: sensirion/.github/.github/workflows/driver.c.check.yml@main
    with:
      examples: '["."]'
      run-environment: "ubuntu-20.04"
