name: Quality check

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  driver-quality:
    uses: sensirion/.github/.github/workflows/driver.c.check.yml@main

  code-generation-check:
    uses: sensirion/.github/.github/workflows/driver.generated.metadata_check.yml@main
